controller_joint_names: ['', 'front_left_j1', 'front_left_j2', 'front_left_j3', 'front_right_j1', 'front_right_j2', 'front_right_j3', 'back_left_j1', 'back_left_j2', 'back_left_j3', 'back_right_j1', 'back_right_j2', 'back_right_j3', ]
